language: python
python:
  - "3.8"
  - "pypy"

before_script:
  - sudo apt-get install pychecker

install:
  - pip install pybuilder
  - pyb install_dependencies

script: "pyb"

notifications:
  email:
  - aelgru@gmail.com
